#!/usr/bin/env bash

DIR=$(cd $(dirname $0); pwd)

if [ -e ~/.vimrc ]; then
  mv ~/.vimrc ~/.vimrc.old
fi

rm -f ~/.vimrc
ln -s $DIR/.vimrc ~/.vimrc

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall! +qall
