#!/usr/bin/env zsh

if [[ -d ~/.ggvm ]]; then
  echo "gvm was already installed."
else
  echo "install gvm"
  git clone https://github.com/moovweb/gvm.git ~/.ggvm
  source ~/.ggvm/binscripts/gvm-installer
fi
